"""add voting status to the VotingConfigTable

Revision ID: 299a7ac030be
Revises: 8b29bc5469fa
Create Date: 2026-05-05 16:28:52.817048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '299a7ac030be'
down_revision: Union[str, Sequence[str], None] = '8b29bc5469fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voting_config', sa.Column('voting_status', sa.Enum('REGISTER', 'VOTE_STARTED', 'VOTE_ENDED', name='votingstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voting_config', 'voting_status')
    # ### end Alembic commands ###
