"""add choices in config db  

Revision ID: 4cb39971ba5f
Revises: 653bfee63e0b
Create Date: 2026-04-07 23:55:12.752186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cb39971ba5f'
down_revision: Union[str, Sequence[str], None] = '653bfee63e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voting_config', sa.Column('choices', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voting_config', 'choices')
    # ### end Alembic commands ###
