"""add config db again 

Revision ID: 653bfee63e0b
Revises: d3ac770cbb4d
Create Date: 2026-04-07 23:50:20.827853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '653bfee63e0b'
down_revision: Union[str, Sequence[str], None] = 'd3ac770cbb4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voting_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emails_sent', sa.Boolean(), nullable=True),
    sa.Column('num_voters', sa.Integer(), nullable=True),
    sa.Column('vote_theme', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voting_config')
    # ### end Alembic commands ###
