"""initial migration

Revision ID: bb338bcfd6db
Revises: 
Create Date: 2026-04-05 23:12:24.437628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb338bcfd6db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counted_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash_n2', sa.String(), nullable=False),
    sa.Column('vote', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('VALID', 'INVALID_SIGNATURE', 'INVALID_N2', name='countedvotestatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_n2')
    )
    op.create_index(op.f('ix_counted_votes_id'), 'counted_votes', ['id'], unique=False)
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('n1', sa.String(), nullable=False),
    sa.Column('hash_n2', sa.String(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_n2'),
    sa.UniqueConstraint('n1')
    )
    op.create_index(op.f('ix_credentials_id'), 'credentials', ['id'], unique=False)
    op.create_table('voters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_voters_id'), 'voters', ['id'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encrypted_vote', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('VALID', 'REJECTED', name='votestatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votes_id'), 'votes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_voters_id'), table_name='voters')
    op.drop_table('voters')
    op.drop_index(op.f('ix_credentials_id'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_counted_votes_id'), table_name='counted_votes')
    op.drop_table('counted_votes')
    # ### end Alembic commands ###
